config/routes.rb
Books::Application.routes.draw do

  resources :books
  resources :sessions
	resources :users
<<<<<<< HEAD
	resources :comentarios
=======
  resources :comentarios
  resources :reviews
  resources :notifications
>>>>>>> 2c05d65856763c0beb1797f8206b8c873954ccdb
  root to: "home#index"
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  attr_accessible :book_id, :description, :receptor, :user_id, :tipo, :leido
  belongs_to :user
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    if logged_in?
      @notifications = Notification.where receptor: current_user.id
      respond_to do |format|
        format.html
        format.json { render json: @notifications }
      end
    else
      flash[:error] = "Necesitas Autenticarte para ver las notificaciones!"
      redirect_to login_path
    end
  end

  def show
    @notification = Notification.find(params[:id])
    @book = Book.find(@notification.book_id)
    @notification[:leido] = true
    @noti = Notification.new
    if params[:disponibilidad]
      @book[:user_pres] = params[:user_pres].to_i
    end
    @notification.update_attributes(params[:notification])
  end

  def new
    @notification = Notification.new
    respond_to do |format|
      format.html
      format.json { render json: @notifications }
    end
  end

  def create
    if logged_in?
      @notification = Notification.new(params[:notification])
      @notification[:description] = params[:description]
      @notification[:book_id] = params[:book_id].to_i
      @notification[:receptor] = params[:receptor].to_i
      @notification[:user_id] = current_user.id
      @notification[:tipo] = params[:tipo].to_i #Tipos: 1=>Prestamo, 2=>Devolucion, 3=>Recordatorio
      @notification[:leido] = false
      respond_to do |format|
        if @notification.save
          if params[:tipo].to_i == 1
            flash[:notice] = "Libro Solicitado!\nEspera la Respuesta."
          else
            if params[:tipo]-to_i == 2
              flash[:notice] = "Libro Disponible!\nYa tienes el libro en tu Inventario."
            end
          end
          format.html { redirect_to books_path}
          format.json { render json: books_path, status: :created, location: books_path }
        else
          format.html { render action: "new" }
          format.json { render json: @notification.errors, status: :unprocessable_entity }
        end
      end
    else
      flash[:error] = "Necesitas Autenticarte para hacer esto!"
      redirect_to login_path
    end
  end

  def destroy
    @notifications = Notification.find(params[:id]).try(:delete)
    respond_to do |format|
      format.html { redirect_to notifications_path }
      format.json { head :no_content }
    end
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/create.html.erb
<h1>Notifications#create</h1>
<p>Find me in app/views/notifications/create.html.erb</p>

app/views/notifications/destroy.html.erb
<h1>Notifications#destroy</h1>
<p>Find me in app/views/notifications/destroy.html.erb</p>

app/views/notifications/index.html.erb
<div class="inicio">
	<h1 class="titulo">Notificaciones</h1><br>
</div>

<div class="tabla">
<ol>
	<% if @notifications %>
		<table class="table table-striped">
		  <thead>
			  <tr>
				  <th>Descripción</th>
				  <th>De</th>
				  <th></th>
				  <th></th>
				  <th></th>
				</tr>
			</thead>
			<% @notifications.each do |noti|%>
			<tbody>
			  <tr>
				  <td><strong><%= (noti.description + (!noti.leido ? " (Nuevo)" : "" )) %></strong></td>
				  <td><strong><%= "#{User.find(noti.user_id).username}" %></strong></td>
					<td><a class="btn btn-info" href=<%=notification_path(noti.id)%>><i class="icon-search icon-white"></i> Ver </a></td>
					<td><a class="btn btn-danger" data-confirm="Estás Seguro?" data-method="delete" href=<%=notification_path(noti) %>><i class="icon-trash icon-white"></i> Borrar </a></td>
				</tr>
			</tbody>
			<%end%>
		</table>
	<%end%>
</ol>

<br />
<br>
<a class="btn btn-inverse" href=<%=user_path(current_user.id)%>><i class="icon-arrow-left icon-white"></i> Atrás </a>
<a class="btn btn-primary" href=<%=new_book_path%>> Agregar Libro </a><br>
<br/>
  <br />
  <br />
</div>
<div class="final"><br></div>

app/views/notifications/new.html.erb
<h1>Notifications#new</h1>
<p>Find me in app/views/notifications/new.html.erb</p>

app/views/notifications/show.html.erb
<div class="autent">
<p>
	<p><h3>De: <%= link_to "#{User.find(@notification.user_id).username}", user_path(@notification.user_id) %></h3></p><hr>
	<p><h3>Asunto:</h3> <h4><%= @notification.description %></h4></p>
	<h3><% if @notification.tipo == 1 %><hr>
		<p>El usuario <%= link_to "#{User.find(@notification.user_id).username}", user_path(@notification.user_id) %> desea que le prestes el libro <%= link_to "#{Book.find(@notification.book_id).titulo}", book_path(@notification.book_id) %>
		</p>
		<% if Book.find(@notification.book_id).disponibilidad %>
			<%= simple_form_for @book do |f| %>
				<%= hidden_field_tag(:noti, true) %>
				<%= hidden_field_tag(:disponibilidad, false) %>
				<%= hidden_field_tag(:user_pres, @notification.user_id) %><br>
				<input class="btn btn-success" type="submit" value="Prestar Libro">
			<% end %>
		<% else %>
			No puedes prestar este libro porque ya lo tiene el usuario <%= link_to "#{User.find(@notification.user_id).username}", user_path(@notification.user_id) %>!
		<% end %>

	<%else%>
		<% if @notification.tipo == 2 %>
			<p>El usuario <%= link_to "#{User.find(@notification.user_id).username}", user_path(@notification.user_id) %> te devolvió el libro <%= link_to "#{Book.find(@notification.book_id).titulo}", book_path(@notification.book_id) %>?
			</p>
			<%= simple_form_for @book do |f| %>
				<%= hidden_field_tag(:noti, true) %>
				<%= hidden_field_tag(:disponibilidad, true) %>
		  	<%= hidden_field_tag(:user_pres, 0) %><br>
		  	<input class="btn btn-success" type="submit" value="Si">
			<% end %>
		<% end %>
	<% end %>
</h3><br><br><br>
	<a class="btn btn-inverse" href=<%=notifications_path%>><i class="icon-arrow-left icon-white"></i> Atrás </a>
</p>
</div>