config/routes.rb
Books::Application.routes.draw do

  resources :books
  resources :sessions
	resources :users
<<<<<<< HEAD
	resources :comentarios
=======
  resources :comentarios
  resources :reviews
  resources :notifications
>>>>>>> 2c05d65856763c0beb1797f8206b8c873954ccdb
  root to: "home#index"
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

end

app/models/user.rb
class User < ActiveRecord::Base  
  has_secure_password
    				attr_accessible :apellido, :password, :email, :fecha_nac, :nombre, :reputacion, :sexo, :username, :password_confirmation
    validates_uniqueness_of :username, :email
    validates_presence_of :apellido, :email, :fecha_nac, :nombre, :sexo, :username

  has_many :comentarios
  has_many :notifications
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
def index
     @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  def show
    @user = User.find(params[:id])
		@comment = Comentario.new
    @comment = Comentario.new
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  def new
     @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  def create
    @user = User.new(params[:user])
    @user[:reputacion] = 10
    respond_to do |format|
     if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to @user, notice: 'Usuario Creado!' }
        format.json { render json: @user, status: :created, location: @user }
     else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if current_user.id == User.find(params[:id])
      respond_to do |format|
        if @user.update_attributes(params[:user])
          format.html { redirect_to @user, notice: 'Usuario Actualizado!' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    else
      flash[:error] = "No puedes Modificar este Usuario!"
      redirect_to @user
    end
  end

  def destroy
    if current_user.id == User.find(params[:id])
      @user = User.find(params[:id])
      @user.destroy

      respond_to do |format|
        format.html { redirect_to users_url }
        format.json { head :no_content }
    	end
    else
      flash[:error] = "No puedes Eliminar este Usuario!"
      redirect_to @user
    end
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :nombre %>
  <%= f.input :apellido %>
  <%= f.label :sexo%>
  <%= f.collection_radio_buttons :sexo, [[true, 'Hombre'] ,[false, 'Mujer']], :first, :last, :checked => true %>
  <%= f.input :fecha_nac, :label =>'Fecha de Nacimiento', :as => :date, :start_year => Date.today.year - 90,
	   			:end_year => Date.today.year, 
          :order => [:day, :month, :year] %>
  <%= f.input :username %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <input class="btn btn-primary" type="submit" value="Listo!">
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<div class="autent">

	<h1 class="titulo">Editing User</h1>

	<%= render 'form' %>

	<a class="btn btn-info" href=<%=user_path(@user.id)%>><i class="icon-search icon-white"></i> Mostrar </a>

</div>

app/views/users/index.html.erb
<div class="inicio">
  <h1 class="titulo">Usuarios</h1><br>
</div>

<div class="tabla">

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Email</th>
        <th>Username</th>
        <th>Nombre</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <% @users.each do |user| %>
    <tbody>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.username %></td>
        <td><%= user.nombre %> <%= user.apellido %></td>
        <td><a class="btn btn-info" href=<%=user_path(user)%>><i class="icon-eye-open icon-black"></i>  Mostrar </a></td>
      </tr>
    </tbody>
    <% end %>
  </table>

  <a class="btn btn-inverse" href=<%=root_url%>><i class="icon-arrow-left icon-white"></i> Atrás </a>
  <a class="btn btn-primary" href=<%=new_user_path%>> Nuevo Usario </a>
  <br/>
  <br />
  <br />
</div>
<div class="final"><br></div>

app/views/users/new.html.erb
<div class="autent">
	<h1 class="titulo">Nuevo Usuario</h1>

	<%= render 'form' %>

	<a class="btn btn-inverse" href=<%=users_path%>><i class="icon-arrow-left icon-white"></i> Atrás </a>
</div>

app/views/users/show.html.erb
<div class="autent" class="user">


<p class="titulo">
  <br><strong>Username:</strong>
  <%= @user.username %>
</p>

<div class="noti">
	<% if logged_in? && current_user.id == @user.id %>
		<a class="btn btn-warning" href=<%=notifications_path%>><i class="icon-search icon-white"></i> Notificaciones </a>
	<%end%><br><br>
</div>

<div class="libros">

<% if logged_in? && current_user.id == @user.id %>
		<br>
		<a class="btn btn-danger" data-confirm="Are you sure?" data-method="delete" href=<%=user_path(@user.id)%>><i class="icon-trash icon-white"></i> Borrar Usuario </a>
		<a class="btn btn-success" href=<%=edit_user_path(@user.id)%>><i class="icon-pencil icon-white"></i> Editar Perfil </a>
		<br><hr>
	<p><h3>Mis Libros:</h3></p>

	<div class="lista">

		<ol>
			<%(Book.where user_id: @user.id).each do |book|%>
				<li><h4><strong><%= link_to "#{book.titulo}", book_path(book.id) %></strong></h4></li><br>
			<% end %>
		</ol>

	</div>

	<br>
	<a class="btn btn-inverse" href=<%=users_path%>><i class="icon-arrow-left icon-white"></i> Atrás </a>
	<a class="btn btn-primary" href=<%=new_book_path%>> Agregar Libro </a><br><br>
<%end%>
<hr>
</div>

<% if !current_user || current_user.id != @user.id %></p>
	<p><strong>Nombre:</strong> <%=@user.nombre%> <%=@user.apellido%></p>
		<p><strong>Fecha de Nacimiento:</strong> <%=@user.fecha_nac.strftime("%d-%m-%Y")%></p>
		<p><strong>E-mail:</strong> <%=@user.email%><hr>
		<p><h3>Libros:</h3></p>
		<div class="lista">	
			<ol>
				<%(Book.where user_id: @user.id).each do |book|%>
					<li><h4><strong><%= link_to "#{book.titulo}", book_path(book.id) %></strong></h4></li><br>
				<% end %>
			</ol>
		</div><hr>
	<br><%= simple_form_for @comment do |f| %>
		<b><%= "Agregue un comentario acerca de este usuario!" %></b>
		<br><br><textarea class="text optional" cols="10" id="comentario_content" name="comentario[contenido]" rows="4"></textarea><br>
 		<%= hidden_field_tag(:perfil, @user.id) %>
 		<input class="btn btn-primary" type="submit" value="Comentar">
	<% end %>
<% end %>

<div class="cometar">

	<br><h3>Comentarios:</h3>
	<%(Comentario.where perfil: @user.id).sort{|x,y| x.created_at <=> y.created_at}.each do |comment|%>
	
		<div class="lista">
			<ol id="comment_list">
				<p><h4><%= link_to "#{User.find(comment.user_id).username}", user_path(comment.user_id) %> escribió</h4></p>
				<p><h4><%= comment.contenido %></h4></p>
			</ol>
		</div>
	<% end %>
	<br><br>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>