config/routes.rb
Books::Application.routes.draw do

  resources :books
  resources :sessions
	resources :users
<<<<<<< HEAD
	resources :comentarios
=======
  resources :comentarios
  resources :reviews
  resources :notifications
>>>>>>> 2c05d65856763c0beb1797f8206b8c873954ccdb
  root to: "home#index"
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :autor, :descripcion, :disponibilidad, :edicion, :t_prestamo, :tipo, :titulo, :user_id, :prestamo, :user_pres
  validates_presence_of :autor, :t_prestamo, :tipo, :titulo

  def self.search(search)
  	if search
    	find(:all, :conditions => ['titulo LIKE ?', "%#{search}%"])
	  else
  	  find(:all)
  	end
	end

	before_validation :clean_titulo, if: "titulo.present?"

	has_many :reviews
	belongs_to :user
  private
  def clean_titulo
    self.titulo = self.titulo.strip.capitalize
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	
	def index
		@books = Book.search(params[:search])
		respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @book }
    end
  end

  def show
		@book=Book.find(params[:id])
		@review = Review.new
		@noti = Notification.new
		respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @book }
    end
  end

  def new
  	if logged_in?
			@book=Book.new
			respond_to do |format|
	      format.html # index.html.erb
	      format.json { render json: @book }
	    end
	  else
      flash[:error] = "Necesitas Autenticarte para hacer esto!"
      redirect_to login_path
    end
  end

  def create
  	if logged_in?
			@book=Book.new(params[:book])
			@book[:disponibilidad] = true
			@book[:user_id] = current_user.id
			@book[:user_pres] = 0
			@book[:t_prestamo] = params[:book][:t_prestamo].to_s
			respond_to do |format|
				if @book.save
					format.html { redirect_to @book, notice: 'Libro Agregado!.' }
	        format.json { render json: @book, status: :created, location: @book }
				else
					format.html { render action: "new" }
	        format.json { render json: @book.errors, status: :unprocessable_entity }
				end
			end
		else
      flash[:error] = "Necesitas Autenticarte para hacer esto!"
      redirect_to login_path
    end
  end

  def edit
		@book=Book.find(params[:id])
  end

  def update
  	if params[:noti]
			@book = Book.find(params[:id])
			@book[:user_pres] = params[:user_pres].to_i
			@book[:disponibilidad] = params[:disponibilidad]
			respond_to do |format|
				if @book.update_attributes(params[:book])
					format.html { redirect_to @book, notice: 'Libro Prestado!.' }
		      format.json { render json: @book, status: :created, location: @book }
				else
					format.html { render action: "new" }
		      format.json { render json: @book.errors, status: :unprocessable_entity }
				end
			end
		else
		 	if current_user.id == Book.find(params[:id]).user_id
				@book=Book.new(params[:book])
				@book[:user_pres] = 0
				respond_to do |format|
					if @book.update_attributes(params[:book])
						format.html { redirect_to @book, notice: 'Libro Actualizado!.' }
		        format.json { render json: @book, status: :created, location: @book }
					else
						format.html { render action: "new" }
		        format.json { render json: @book.errors, status: :unprocessable_entity }
					end
				end
			else
		    flash[:error] = "No puedes modificar las propiedades de este Libro!"
		    redirect_to @book
		  end
		end
  end

  def destroy
  	if current_user.id == Book.find(params[:id]).user_id
			Book.find(params[:id]).try(:delete)
			respond_to do |format|
	      format.html { redirect_to books_path }
	      format.json { head :no_content }
	  	end
	  else
      flash[:error] = "No puedes eliminar este Libro!"
      redirect_to @book
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%=simple_form_for @book do |f|%>
	<% if @book.errors.any?%>
		<div class="alert alert-error">
      <a class="close" data-dismiss="alert">×</a>
			<h3>There were errors!</h3>
			<% @book.errors.full_messages.each do |msg| %>
				<%= msg %><br>
			<% end %>
		</div>
	<%end%>

	<p>
		<%=f.input :titulo %>
		<%=f.input :autor %>
		<%=f.input :tipo %>
		<%=f.input :edicion %>
		<%=f.input :descripcion %>
		<%= f.collection_radio_buttons :prestamo, [[true, 'Dias'] ,[false, 'Meses']], :first, :last, :checked => true %>
		<%= hidden_field_tag(:noti, false) %>
		<%=f.input :t_prestamo, :as => :integer %>
	</p>
		<input class="btn btn-primary" type="submit" value="Listo!">
	
<%end%>

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/destroy.html.erb
<ol>
  <% @books.each do |book|%>
    <li>
      	<%= book.titulo %>
		<%= book.autor %>
      	<%= link_to "show code", code %>
      	<%= link_to "delete", book, :method => :delete, :confirm => "Esta Seguro?" %>
   </li>
  <% end %>
</ol>
<a class="btn btn-inverse" href=<%=new_book_path%>> Agregar Libro </a>

app/views/books/edit.html.erb
<div class="autent">

<h1 class="titulo"> Edit a Book </h1>
<%= render 'form' %>
<a class="btn btn-inverse" href=<%= book_path(@book) %>><i class="icon-arrow-left icon-white"></i> Atrás </a>
</div>

app/views/books/index.html.erb
<div class="inicio">
  <h1 class="titulo">All Books</h1><br>
</div>
<% form_tag books_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Buscar", :titulo => nil %>
  </p>
<% end %>
<div class="tabla">
<table class="table table-striped">
  <thead>
    <tr>
      <th>Título</th>
      <th>Autor</th>
      <th>Dueño</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
<% if @books %>
	<% @books.each do |book|%>
  <tbody>
	  <tr>
	    <td><%=book.titulo %></td>
	    <td><%=book.autor %></td>
	    <td><%= link_to "#{User.find(book.user_id).username}", user_path(book.user_id) %></td>
	    <td><a class="btn btn-info" href=<%=book_path(book.id)%>><i class="icon-eye-open icon-black"></i> Mostrar </a></td>
	  </tr>
  </tbody>
	<% end %>
<% end %>
</table>


<br>
<br><a class="btn btn-inverse" href=<%=root_url%>><i class="icon-arrow-left icon-white"></i> Atrás </a>
<a class="btn btn-primary" href=<%=new_book_path%>> Agregar Libro </a><br>
<br/>
  <br />
  <br />
</div>
<div class="final"><br></div>

app/views/books/new.html.erb
<div class="autent">

<h1 class="titulo"> Create a Book </h1>
<%= render 'form'%> 
<a class="btn btn-inverse" href=<%=books_path%>><i class="icon-arrow-left icon-white"></i> Atrás </a>
</div>

app/views/books/show.html.erb
<div class="contenedor">
<div class="arriba"></div>
<div class="centro">
<p>
	<p class="centro"><strong>Dueño:</strong> <%= "#{User.find(@book.user_id).username}" %></p>
	<p class="centro"><strong>Título:</strong> <%=@book.titulo%></p>
	<p class="centro"><strong>Autor:</strong> <%=@book.autor%></p>
	<p class="centro"><strong>Tipo:</strong> <%= @book.tipo %></p>
	<p class="centro"><strong>Edición:</strong> <%= @book.edicion %></p>
	<p class="centro"><strong>Descripción:</strong> <%= @book.descripcion %></p>
	<p class="centro"><strong>Tiempo de préstamo:</strong> <%= "#{@book.t_prestamo} #{@book.prestamo ? "Dias" : "Meses" }" %></p>
	<p class="centro"><strong>Disponible:</strong> <%= "#{@book.disponibilidad ? "Si" : "No" }" %></p><br>
	<% if logged_in? && current_user.id == @book.user_id %>
		<a class="btn btn-danger" data-confirm="Are you sure?" data-method="delete" href=<%=book_path(@book.id)%>><i class="icon-trash icon-white"></i> Borrar </a>
		<a class="btn btn-success" href=<%=edit_book_path(@book.id)%>><i class="icon-pencil icon-white"></i> Editar </a>
	<% end %>
	<% if !current_user || current_user.id != @book.user_id %>
		<% if @book.disponibilidad %>
			<%= simple_form_for @noti do |f| %>
	  		<%= hidden_field_tag(:description, "Prestamo de Libro") %>
		  	<%= hidden_field_tag(:book_id, @book.id) %>
		  	<%= hidden_field_tag(:receptor, @book.user_id) %>
	  		<%= hidden_field_tag(:tipo, 1) %>
  			<input class="btn btn-success" type="submit" value="Pedir Prestado">
			<% end %>
		<% else %>
			<% if current_user.id == @book.user_pres %>
				<%= simple_form_for @noti do |f| %>
	  		<%= hidden_field_tag(:description, "Devolver Libro") %>
		  	<%= hidden_field_tag(:book_id, @book.id) %>
		  	<%= hidden_field_tag(:receptor, @book.user_id) %>
	  		<%= hidden_field_tag(:tipo, 2) %>
	  		<%= hidden_field_tag(:disponibilidad, true) %>
  			<input class="btn btn-success" type="submit" value="Devolver Libro">
			<% end %>
		<% end %>
	<% end %>

		<p>
		<%= simple_form_for @review do |f| %>
			<%= "Agregue la primera reseña!" %>
			<br><br><textarea class="text optional" cols="10" id="comentario_content" name="review[contenido]" rows="4"></textarea><br>
  		<%= hidden_field_tag(:book_id, @book.id) %>
  		<input class="btn btn-primary" type="submit" value="Reseñar">
		<% end %>
		</p>
	<% end %>
</p>
<a class="btn btn-inverse" href=<%=books_path%>><i class="icon-arrow-left icon-white"></i> Atrás </a><br>
<% if logged_in? && current_user.id == @book.user_id %>
<div class="duenio"></div>
<%end%>
<div class="review">
<br> <h3>Reseñas</h3><br>
<%(Review.where book_id: @book.id).sort{|x,y| x.created_at <=> y.created_at}.each do |review|%>
	<ul id="review_list">
		<h4><%= link_to "#{User.find(review.user_id).username}", user_path(review.user_id) %> escribió:</h4>
			<p><h5><%= review.contenido %></h5></p>
	</ul>
<% end %>
</div>
</div>
<div class="abajo"></div>
</div>

app/views/books/update.html.erb
<h1>All Books</h1>