config/routes.rb
Books::Application.routes.draw do

  resources :books
  resources :sessions
	resources :users
<<<<<<< HEAD
	resources :comentarios
=======
  resources :comentarios
  resources :reviews
  resources :notifications
>>>>>>> 2c05d65856763c0beb1797f8206b8c873954ccdb
  root to: "home#index"
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es-419">
<head>
  <meta charset="utf-8" />
  <title>Books</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link rel="shortcut icon" href="http://www.iconj.com/ico/t/w/tw4rtyh42n.ico" type="image/x-icon" />
  <%= stylesheet_link_tag "bootstrap/css/bootstrap.css"%>
 	<link rel="stylesheet" type="text/css" href="estilos.css">
</head>
<body>
  <div class="navbar">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="/">Book Store</a>
        <div class="nav-collapse">
            <ul class="nav pull-right">
              <% unless logged_in? %>
                <li><a href=<%=signup_path%>> <b>Crear Cuenta</b> </a></li>
                <li><a href=<%=login_path%>> <b>Autenticarse</b> </a></li>
              <% else %>
                <li><a href=<%=user_path(current_user.id)%>> <b><%= current_user.username %></b> </a></li>
                <li><a href=<%=logout_path%>> <b>Salir</b> </a></li>
              <%end%>
            </ul>
        </div>
      </div>
    </div>
  </div>

	<div class="container">
		<% if flash[:notice] %>
      <div class="alert alert-success">
        <a class="close" data-dismiss="alert">×</a>
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:error] %>
      <div class="alert alert-error">
        <a class="close" data-dismiss="alert">×</a>
        <%= flash[:error] %>
      </div>
    <% end %>

    <%= yield %>
</body>
</html>